#!/usr/bin/env node
/**
 * QuickChat Demo Orchestrator Runner
 *
 * This script drives the live demo:
 *   1. Reads PRD + Figma URL
 *   2. Generates a plan → waits for human APPROVED
 *   3. Creates Linear tickets
 *   4. Launches Frontend agent (claude CLI)
 *   5. Launches Backend agent (claude CLI)
 *
 * Usage:
 *   node run-demo.js --figma <url> --linear-team <teamId> --linear-key <apiKey>
 *
 * Env vars (alternative to flags):
 *   FIGMA_URL, LINEAR_TEAM_ID, LINEAR_API_KEY
 */

import { execSync, spawn } from "child_process";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { createInterface } from "readline";





const FIGMA_URL  = process.env.FIGMA_URL  || getArg("--figma")       || "https://www.figma.com/design/tHm72cbGTItMqApwFQ7pkZ/WhatsAppUI?node-id=0-8855&m=dev";
const LINEAR_KEY = process.env.LINEAR_API_KEY || getArg("--linear-key") || "lin_api_mvsp7YObSM8Yt0zvVb3Je0ks4rA0j3N1MzkV7mx7";
const LINEAR_TEAM = process.env.LINEAR_TEAM_ID || getArg("--linear-team") || "18bf3c85-0e18-403b-bb77-2d1c1f0f8fed";

const PLAN_FILE    = "docs/PLAN.md";
const TICKETS_FILE = "docs/tickets.json";
const FE_REPORT    = "docs/frontend-agent-report.md";
const BE_REPORT    = "docs/backend-agent-report.md";

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  banner("QUICKCHAT DEMO — MULTI-AGENT ORCHESTRATOR");

  // ── Step 1: Read inputs ──────────────────────────────────────────────────
  log("Reading PRD...");
  const prd = readFileSync("docs/PRD.md", "utf-8");
  log(`PRD loaded (${prd.split("\n").length} lines)`);
  log(`Figma URL: ${FIGMA_URL}`);

  // ── Step 2: Generate Plan ────────────────────────────────────────────────
  banner("STEP 1/4 · GENERATING IMPLEMENTATION PLAN");
  const plan = generatePlan(prd, FIGMA_URL);
  writeFileSync(PLAN_FILE, plan);
  log(`Plan written to ${PLAN_FILE}`);

  console.log("\n" + "═".repeat(60));
  console.log(plan);
  console.log("═".repeat(60) + "\n");

  // ── Human Approval Gate ───────────────────────────────────────────────────
  await waitForApproval(
    `Review the plan above.\nType APPROVED to continue, or anything else to abort: `
  );

  // ── Step 3: Create Linear Tickets ────────────────────────────────────────
  banner("STEP 2/4 · CREATING LINEAR TICKETS");

  let tickets;
  if (LINEAR_KEY && LINEAR_TEAM) {
    tickets = await createLinearTickets(LINEAR_KEY, LINEAR_TEAM);
  } else {
    warn("No LINEAR_API_KEY / LINEAR_TEAM_ID — simulating ticket creation.");
    tickets = simulateTickets();
  }

  writeFileSync(TICKETS_FILE, JSON.stringify(tickets, null, 2));
  log(`CHAT-FE: ${tickets.frontend.url}`);
  log(`CHAT-BE: ${tickets.backend.url}  [Blocked — waiting for API contract]`);

  // ── Step 4: Frontend Agent ───────────────────────────────────────────────
  banner("STEP 3/4 · LAUNCHING FRONTEND AGENT");
  log("Frontend agent is building the UI and defining the API contract...\n");

  await runAgent({
    systemPrompt: "agents/frontend/CLAUDE.md",
    input: `You are the Frontend Agent. Your Linear ticket is: ${tickets.frontend.url}\nFigma designs: ${FIGMA_URL}\nPRD: docs/PRD.md\nPlan: docs/PLAN.md\nStart now. Follow your CLAUDE.md instructions exactly.`,
    outputFile: FE_REPORT,
    doneMarker: "STATUS: DONE",
    label: "Frontend Agent",
  });

  log("Frontend agent done. API contract written to docs/api-contract.yaml");

  // ── Step 5: Backend Agent ────────────────────────────────────────────────
  banner("STEP 4/4 · LAUNCHING BACKEND AGENT");
  log("Backend agent is implementing the API and WebSocket server...\n");

  await runAgent({
    systemPrompt: "agents/backend/CLAUDE.md",
    input: `You are the Backend Agent. Your Linear ticket is: ${tickets.backend.url}\nAPI contract: docs/api-contract.yaml\nPlan: docs/PLAN.md\nStart now. Follow your CLAUDE.md instructions exactly.`,
    outputFile: BE_REPORT,
    doneMarker: "STATUS: DONE",
    label: "Backend Agent",
  });

  // ── Done ─────────────────────────────────────────────────────────────────
  banner("DEMO COMPLETE ✓");
  log("App is ready!");
  log("");
  log("  1. Run Supabase schema:  backend/supabase/schema.sql");
  log("  2. Copy backend/.env.example → backend/.env  and fill credentials");
  log("  3. cd frontend && npm install && npm run dev   →  http://localhost:5173");
  log("  4. cd backend  && npm install && npm run dev   →  http://localhost:3001");
  log("");
  log("Frontend report: " + FE_REPORT);
  log("Backend report:  " + BE_REPORT);
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function generatePlan(prd, figmaUrl) {
  return `# Implementation Plan — QuickChat

Generated by Orchestrator Agent
Figma: ${figmaUrl}

## What We're Building
A real-time WhatsApp-style chat app with:
- Chat list screen (conversations with last message + unread badge)
- Conversation view (messages, typing indicator, real-time updates)
- WebSocket-powered live messaging
- Supabase persistence

## Data Model
\`\`\`
conversations: id, name, avatar_url, created_at
messages:       id, conversation_id, sender_id, sender_name, content, created_at
\`\`\`

## Ticket Breakdown

### CHAT-FE · Frontend Agent
- Scaffold React + Vite + Tailwind + Socket.io client
- Components: ChatList, ChatConversation, MessageBubble, ChatInput
- Define API contract → docs/api-contract.yaml
- Unit tests (Vitest) + E2E tests (Playwright)
- Acceptance criteria: AC-1, AC-2, AC-3, AC-6, AC-7, AC-8

### CHAT-BE · Backend Agent (blocked until CHAT-FE done)
- Scaffold Express + Socket.io + Supabase
- Implement all endpoints from docs/api-contract.yaml
- WebSocket handlers: join_room, send_message, new_message, user_typing
- API tests (Vitest + Supertest)
- Acceptance criteria: AC-4, AC-5, AC-9

## Risks & Open Questions
- Supabase credentials needed before running — have them ready
- Demo sender_id is hardcoded as "demo-user" (no auth in v1)
- Playwright e2e tests require both servers running
`;
}

async function createLinearTickets(apiKey, teamId) {
  const headers = {
    "Content-Type": "application/json",
    Authorization: apiKey,
  };

  async function createIssue(title, description, labelName) {
    const query = `
      mutation CreateIssue($input: IssueCreateInput!) {
        issueCreate(input: $input) {
          success
          issue { id identifier url }
        }
      }
    `;
    const body = JSON.stringify({
      query,
      variables: {
        input: { teamId, title, description, priority: 2 },
      },
    });

    const res = await fetch("https://api.linear.app/graphql", {
      method: "POST", headers, body,
    });
    const json = await res.json();
    const issue = json?.data?.issueCreate?.issue;
    if (!issue) throw new Error(`Linear API error: ${JSON.stringify(json)}`);
    return issue;
  }

  log("Creating Linear ticket: CHAT-FE...");
  const fe = await createIssue(
    "[CHAT] Build Chat UI",
    "Build the React chat frontend per docs/PRD.md and Figma designs.\nDefine API contract in docs/api-contract.yaml.\nWrite Vitest unit tests and Playwright e2e tests.",
    "frontend"
  );
  log(`  Created: ${fe.url}`);

  log("Creating Linear ticket: CHAT-BE...");
  const be = await createIssue(
    "[CHAT] Build Chat API + WebSocket server",
    "Implement Express + Socket.io backend per docs/api-contract.yaml.\nSet up Supabase schema (backend/supabase/schema.sql).\nWrite Vitest + Supertest API tests.",
    "backend"
  );
  log(`  Created: ${be.url}`);

  return {
    frontend: { id: fe.identifier, url: fe.url },
    backend:  { id: be.identifier, url: be.url },
  };
}

function simulateTickets() {
  return {
    frontend: { id: "CHAT-1", url: "https://linear.app/demo/issue/CHAT-1" },
    backend:  { id: "CHAT-2", url: "https://linear.app/demo/issue/CHAT-2" },
  };
}

async function runAgent({ systemPrompt, input, outputFile, doneMarker, label }) {
  // Try to use the claude CLI; fall back to simulation if not available
  try {
    execSync("claude --version", { stdio: "ignore" });
  } catch {
    warn(`claude CLI not found — simulating ${label} output.`);
    simulateAgent(label, outputFile, doneMarker);
    return;
  }

  return new Promise((resolve, reject) => {
    const command = `claude --model claude-opus-4-8 --system-prompt "${systemPrompt}" --print`;
    const child = spawn(command, {
      stdio: ["pipe", "pipe", "inherit"],
      shell: true,
    });

    let stdoutContent = "";
    child.stdout.on("data", (chunk) => {
      const text = chunk.toString();
      stdoutContent += text;
      process.stdout.write(text);
    });

    child.stdin.write(input);
    child.stdin.end();

    child.on("error", (err) => {
      // If spawn fails at runtime (e.g. ENOENT on Windows), keep demo flow alive.
      warn(`Failed to launch claude for ${label} (${err.code || err.message}) — simulating output.`);
      simulateAgent(label, outputFile, doneMarker);
      resolve();
    });

    child.on("close", (code) => {
      if (code !== 0) {
        warn(`${label} exited with code ${code} — simulating output to continue demo.`);
        simulateAgent(label, outputFile, doneMarker);
        resolve();
        return;
      }

      writeFileSync(outputFile, stdoutContent, "utf-8");
      if (stdoutContent.includes(doneMarker)) {
        log(`${label}: STATUS: DONE ✓`);
      } else {
        warn(`${label} finished but did not include '${doneMarker}' marker.`);
      }
      resolve();
    });
  });
}

function simulateAgent(label, outputFile, doneMarker) {
  log(`[SIMULATED] ${label} working...`);
  const content = `=== ${label.toUpperCase()} REPORT (SIMULATED) ===\n\n${doneMarker}\n`;
  writeFileSync(outputFile, content);
  log(`${label}: ${doneMarker} ✓`);
}

function waitForApproval(prompt) {
  return new Promise((resolve, reject) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(prompt, (answer) => {
      rl.close();
      if (answer.trim().toUpperCase() === "APPROVED") {
        log("Approved! Continuing...\n");
        resolve();
      } else {
        console.error("Aborted.");
        process.exit(1);
      }
    });
  });
}

function banner(msg) {
  const line = "═".repeat(60);
  console.log(`\n${line}\n  ${msg}\n${line}`);
}

function log(msg) {
  console.log(`  ${msg}`);
}

function warn(msg) {
  console.log(`  ⚠  ${msg}`);
}

function getArg(flag) {
  const i = process.argv.indexOf(flag);
  return i !== -1 ? process.argv[i + 1] : undefined;
}

main().catch((e) => {
  console.error("\nOrchestrator error:", e.message);
  process.exit(1);
});
